export const  GET_FAST_RIDER_DATA_REQUEST= "GET_FAST_RIDER_DATA_REQUEST";
export const  GET_FAST_RIDER_DATA_SUCCESS= "GET_FAST_RIDER_DATA_SUCCESS";
export const  GET_FAST_RIDER_DATA_FAILURE= "GET_FAST_RIDER_DATA_FAILURE";

export const  SET_SELECTED_RIDE_REQUEST= "SET_SELECTED_RIDE_REQUEST";
export const  SET_SELECTED_RIDE_SUCCESS= "SET_SELECTED_RIDE_SUCCESS";
export const  SET_SELECTED_RIDE_FAILURE= "SET_SELECTED_RIDE_FAILURE";

export const  SUBMIT_RIDE_REQUEST= "SUBMIT_RIDE_REQUEST";
export const  SUBMIT_RIDE_SUCCESS= "SUBMIT_RIDE_SUCCESS";
export const  SUBMIT_RIDE_FAILURE= "SUBMIT_RIDE_FAILURE";

export const  SET_ERROR_MESSAGE= "SET_ERROR_MESSAGE";
export const  CHANGE_SUCCESS_ON_REDIRECT= "CHANGE_SUCCESS_ON_REDIRECT";